//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Labyrinth
{
	public static class Utils
	{
		public static void LogInfo(string formatString, params object[] args)
		{
			var msg = string.Format (formatString, args);
			Debug.Log (string.Format("[{0}]: {1}", DateTime.Now.ToShortTimeString(), msg));
		}
	}
}
